name: fortune_spinner_example
description: "Example app for fortune_spinner package."
publish_to: "none"

version: 1.0.0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  fortune_spinner:
    path: ../

  cupertino_icons: ^1.0.8




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_gen_runner: ^5.10.0
  build_runner: ^2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

flutter_gen:
  integrations:
    flutter_svg: true